apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: es-data
  labels:
    component: elasticsearch
    role: data
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: elasticsearch
        role: data
    spec:
      initContainers:
        - name: init-sysctl
          image: busybox:1.27.2
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          securityContext:
            privileged: true
      containers:
        - name: es-data
          image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CLUSTER_NAME
              value: $CLUSTER_NAME
            - name: NODE_MASTER
              value: "false"
            - name: NODE_INGEST
              value: "false"
            - name: HTTP_ENABLE
              value: "false"
            - name: ES_JAVA_OPTS
              value: $ES_JAVA_OPTS
            - name: ES_PLUGINS_INSTALL
              value: $ES_PLUGINS_INSTALL
          ports:
            - containerPort: $PORT_TRANSPORT
              name: transport
          livenessProbe:
            tcpSocket:
              port: transport
            initialDelaySeconds: 120
            periodSeconds: 20
          volumeMounts:
            - name: $GCE_DISK
              mountPath: /data
      volumes:
        - name: $GCE_DISK
          persistentVolumeClaim:
            claimName: $GCE_DISK
